local Character = {
	SprintSpeed = 26,
	WalkSpeed = 20,
	JumpPower = 35,
	AutoSprint = false,
	CoyoteTime = 0.12,
	WallJump = {
		Enabled = true,
		VerticalBoost = 37.74,
		HorizontalBoost = 25,
		WallPushForce = 35,
		AnglePushMultiplier = 1.5,
		WallDetectionDistance = 3.0,
		MinWallAngle = 30,
		RequireAirborne = true,
		RequireSprinting = false,
		ExcludeDuringSlide = true,
		MaxCharges = 3,
		CooldownBetweenJumps = 0.3,
	},
	Jump = {
		WallRaycast = {
			Enabled = true,
			RayDistance = 2.5,
			MinWallAngle = 75,
		},
		CrouchCancel = {
			Enabled = true,
			VelocityCancelMultiplier = 0.1,
			MinAirborneTime = 0.1,
			DownforceOnCancel = 80,
		},
	},
	MovementForce = 500,
	FrictionMultiplier = 0.95,
	AirControlMultiplier = 0.18,
	AirResistance = 25.12,
	AirborneSlideDownforce = 600,
	FallSpeed = {
		Enabled = true,
		MaxFallSpeed = 150,
		DragMultiplier = 0.15,
		AscentDrag = 0.01,
		FallAcceleration = 40,
		AscentGravityReduction = 0.50,
		HangTimeThreshold = 8,
		HangTimeDrag = 0.05,
	},
	GravityDamping = {
		Enabled = true,
		DampingFactor = 0.60,
		MaxFallSpeed = 200,
		ApplyOnlyWhenFalling = true,
	},
	FloatDecay = {
		Enabled = true,
		FloatDuration = 0.8,
		DecayRate = 0.08,
		MinDampingFactor = 0.20,
		MomentumFactor = 0.010,
		VelocityThreshold = 0.6,
		ThresholdShrinkRate = 0.003,
	},
	LandingMomentum = {
		Enabled = true,
		PreservationMultiplier = 0.8,
		MinPreservationSpeed = 15,
		DecayRate = 0.92,
	},
	WallStop = {
		Enabled = true,
		RayDistance = 1.5,
		MinWallAngle = 70,
	},
	-- Slope Magnet (snap to ground when about to launch off ramps/slopes)
	-- Keeps grounded state stable on sloped collision seams so walking uphill doesn't "airborne flicker".
	SlopeMagnet = {
		Enabled = true,
		RayLength = 3.0,
		SnapVelocity = -80,
		JumpCooldown = 0.25,
		MinAirborneHeight = 0.5,
	},
	GroundRayOffset = 0.25,
	GroundRayDistance = 0.6,
	MaxWalkableSlopeAngle = 90,
	StandingFriction = {
		IdleFriction = 0.65,
		MinSlopeAngle = 1,
		SlopeFriction = 1.1,
	},
	CrouchHeightReduction = 2,
	CrouchSpeed = 8,
	CrouchSpeedReduction = 0.5,
	DirectionalAnimations = {
		ForwardAngle = 60,
		LateralStartAngle = 60,
		LateralEndAngle = 120,
		BackwardStartAngle = 120,
		BackwardEndAngle = 240,
	},
	HeadOffset = Vector3.new(0, 2, 0),
	HideFromLocalPlayer = true,
	PartsToHide = { "Body", "Feet", "Head", "Root", "CrouchBody", "CrouchHead" },
	ShowRigForTesting = false,
	EnableRig = true,
	CustomPhysicalProperties = {
		Density = 0.7,
		Elasticity = 0,
		ElasticityWeight = 100,
		Friction = 0,
		FrictionWeight = 100,
	},
	DeathYThreshold = -100,
	RigRotation = {
		Enabled = true,
		MaxTiltAngle = 55,
		Smoothness = 38,
		MinSlopeForRotation = 3,
		Airborne = {
			Enabled = true,
			MaxTiltAngle = 18,
			MinVerticalVelocity = 6,
			Smoothness = 10,
		},
	},
	Ragdoll = {
		Physics = {
			Density = 0.7,
			Friction = 0.5,
			Elasticity = 0,
			HeadDensity = 0.7,
			HeadFriction = 0.3,
		},
		JointLimits = {
			Neck = {
				UpperAngle = 45,
				TwistLowerAngle = -60,
				TwistUpperAngle = 60,
				MaxFrictionTorque = 10,
			},
			Shoulder = {
				UpperAngle = 90,
				TwistLowerAngle = -75,
				TwistUpperAngle = 75,
				MaxFrictionTorque = 5,
			},
			Hip = {
				UpperAngle = 90,
				TwistLowerAngle = -45,
				TwistUpperAngle = 45,
				MaxFrictionTorque = 5,
			},
			RootJoint = {
				UpperAngle = 30,
				TwistLowerAngle = -45,
				TwistUpperAngle = 45,
				MaxFrictionTorque = 15,
			},
		},
		AutoRagdoll = {
			OnDeath = true,
			OnExplosion = false,
			OnHighVelocity = false,
			VelocityThreshold = 100,
		},
		DeadRagdoll = {
			FadeTime = 5,
			FadeDuration = 0.3,
		},
	},
}

return Character
